apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-frontend
  template:
    metadata:
      labels:
        app: book-frontend
    spec:
      containers:
        - name: web
          image: ghcr.io/ryusid/book-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: book-frontend-config

