apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yml
  - backend-service.yml
  - frontend-deploy.yml
  - frontend-svc.yml
  - ingress-api.yml
  - ingress-frontend.yml
  - frontend-config.yml
  - pvc.yaml
images:
  - name: ghcr.io/ryusid/book-frontend
    newTag: sha-674cd29
  - name: ghcr.io/ryusid/book-backend
    newTag: sha-dc05be2
